[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
verbosity = 3

remappings = ["openzeppelin-contracts/=lib/openzeppelin-contracts/contracts"]

gas_reports_ignore = ["MockERC20"]


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
